New Time Smearing Module for Neutral Particles and FCC-hh Card
selvaggi/delphes pull request #5
Opened 2020-01-06 21:16 UTC by kaanyuxel

New Time Smearing Module for Neutral Particles and FCC-hh Detector Card Update

2020-01-07 13:20 UTC, selvaggi requested changes
Thanks for this. 
Please see comments inline.

2020-01-07 13:20 UTC, selvaggi commented on modules/TimeSmearingNeutral.cc
> +/*
Why do we need a new module? 
Can't we just modify TimeSmearing to allow for both neutral and MIPs?
And then just call it in the card as: 

TimeSmearing TimeSmearingNeutral
TimeSmearing TimeSmearingMIP

2020-01-07 13:20 UTC, selvaggi commented on modules/TrackTimingPileUpSubtractor.cc
> +  fZVertexResolution = GetDouble("ZVertexResolution", 3);
I think this naming is confusing.
Shouldn't we use instead something like:

fNeutralMinSignificance
fChargedMinSignificance

2020-01-09 00:42 UTC, kaanyuxel commented
Hey Michele, I have finished your requests

2020-01-24 14:55 UTC, merged